title: StackExchange Tagger
description: "Tagger for questions posted on StackExchange Network "
google_analytics: UA-58193601-2
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
